<script lang="ts">
  import { onMount } from 'svelte';
  import ArrowRight from '@lucide/svelte/icons/arrow-right';
  import Check from '@lucide/svelte/icons/check';
  import LockKeyhole from '@lucide/svelte/icons/lock-keyhole';
  import Trash2 from '@lucide/svelte/icons/trash-2';
  import X from '@lucide/svelte/icons/x';
  import { clearPrivateData, loadSessions, type Session } from '$lib/storage';
  import { deleteAdaptiveProfile, getProfileInsights, type ProfileInsights } from '$lib/api';
  export let revision = 0; export let onCheckIn: () => void;
  let confirmClear = false; let sessions: Session[] = loadSessions(); let remote: ProfileInsights | null = null; let backendState: 'loading' | 'ready' | 'unavailable' = 'loading';
  $: sessions = (revision, loadSessions());
  $: displaySessions = remote?.consented ? remote.sessions.map((session): Session => ({ id: session.id, createdAt: session.createdAt, interventionId: session.practiceId, before: session.before, after: session.after, outcome: session.outcome, completed: session.completed, modelVersion: session.modelVersion, policySource: 'adaptive-v3' })) : sessions;
  $: rated = displaySessions.filter((session) => session.outcome); $: helpful = rated.filter((session) => session.outcome === 'helped').length;
  $: harder = rated.filter((session) => session.outcome === 'harder').length; $: completed = displaySessions.filter((session) => session.completed).length;
  $: stopped = displaySessions.filter((session) => !session.completed).length; $: rate = rated.length ? Math.round(helpful / rated.length * 100) : 0;
  $: points = displaySessions.filter((session) => Number.isFinite(session.after)).slice(0, 7).reverse();
  $: chartPoints = points.map((session, index) => `${20 + index * 55},${130 - Number(session.after) / 10 * 95}`).join(' ');
  onMount(async () => { try { remote = await getProfileInsights(); backendState = 'ready'; } catch { backendState = 'unavailable'; } });
  async function clear() { if (remote?.consented) { try { await deleteAdaptiveProfile(); } catch { /* local reset remains available */ } } clearPrivateData(); sessions = []; remote = null; confirmClear = false; }
</script>

<main id="main-content" class="insights-page page-shell"><div class="page-kicker"><span class="pill pill-sage"><LockKeyhole /> Response Map</span></div>
  <div class="insights-heading"><div><span class="eyebrow coral">Your adaptive loop</span><h1>What helped.<br /><em>What changes next.</em></h1></div><p>Every explicit outcome becomes evidence for the next safe decision. No after-score or response is inferred.</p></div>
  <section class="stats-grid"><article><span>Decisions</span><strong>{displaySessions.length || '—'}</strong><small>{displaySessions.length ? `${completed} completed · ${stopped} stopped` : 'Your first explicit session starts the map'}</small></article><article><span>Helpful steps</span><strong>{rated.length ? `${rate}%` : '—'}</strong><small>{harder ? `${harder} marked harder and excluded` : 'Based only on explicit feedback'}</small></article><article class="accent"><span>Policy source</span><strong>{remote?.consented ? 'Adaptive' : 'Local'}</strong><small>{backendState === 'unavailable' ? 'Server unavailable; local history shown' : remote?.consented ? 'Anonymous profile · 30-day event retention' : 'Opt in during check-in to enable learning'}</small></article></section>
  <div class="insights-grid"><section class="pattern-card"><div class="card-heading"><div><span class="eyebrow">Explicit measurements</span><h2>Your reported response map</h2></div><span class="pill">{points.length ? 'Measured by you' : 'Waiting for data'}</span></div>
    {#if points.length}<div class="line-chart"><div class="y-labels"><span>10</span><span>5</span><span>0</span></div><svg viewBox="0 0 380 150" role="img" aria-label="Recent explicitly reported after-intensity scores"><line x1="20" y1="35" x2="360" y2="35"></line><line x1="20" y1="82" x2="360" y2="82"></line><line x1="20" y1="130" x2="360" y2="130"></line><polyline points={chartPoints}></polyline>{#each points as session, index}<circle cx={20 + index * 55} cy={130 - Number(session.after) / 10 * 95} r="5"><title>{session.completed ? 'Completed' : 'Stopped'} · {session.outcome ?? 'feedback skipped'} · intensity {session.after}</title></circle>{/each}</svg></div><div class="session-legend">{#each points as session}<span class={`outcome-${session.outcome ?? 'none'}`}>{session.completed ? 'Completed' : 'Stopped'} · {session.outcome ?? 'measurement only'} · {session.policySource === 'adaptive-v3' ? 'adaptive' : 'local'}</span>{/each}</div>
    {:else}<div class="empty-pattern"><div><i></i><i></i><i></i></div><h3>No response pattern yet.</h3><p>Complete a practice and optionally report one explicit measurement.</p><button onclick={onCheckIn}>Try a check-in <ArrowRight /></button></div>{/if}
  </section><section class="model-card"><span class="eyebrow">Data & control</span><h2>{remote?.consented ? 'Anonymous adaptive profile.' : 'Local resilience policy.'}</h2><div class="knows-row"><Check /><span><b>Explicit outcomes</b><small>Helped / same / harder directly updates the selected arm</small></span></div><div class="knows-row"><Check /><span><b>Bounded decision context</b><small>Signals, need, intensity, time, and access settings for consented events</small></span></div><div class="knows-row"><Check /><span><b>Optional after-intensity</b><small>Charted as reported and never converted into a reward</small></span></div><div class="knows-row muted"><X /><span><b>No story or identity</b><small>No name, diagnosis, free text, IP address, or user-agent is retained</small></span></div><button class="delete-button" onclick={() => confirmClear = true}><Trash2 /> Reset my response model</button>{#if confirmClear}<div class="confirm-clear"><p>This removes local history and, when enabled, deletes the anonymous server profile and retained events.</p><div><button onclick={clear}>Reset everything</button><button onclick={() => confirmClear = false}>Cancel</button></div></div>{/if}</section></div>
</main>
